spring:
  application:
    name: api-gateway
  aop:
      proxy-target-class: true
server:
  port: 7777
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    company-service: /api/company/**
    process-service: /api/process/**
    document-service: /api/document/**
    descriptor-service: /api/descriptor/**
    auth-service: /api/uaa/**
  retryable: true
ribbon:
  eager-load:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
