server:
  port: 8081
spring:
  application:
    name: company-service
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
