server:
  port: 8083
addToDb: true
spring:
  application:
    name: descriptor-service
  http:
    multipart:
     max-file-size: 1024KB
     max-request-size: 1024KB
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/descriptor?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      bindings:
        documentAddedOutput:
          destination: documentAdded
          contentType: application/json
        documentDeletedInput:
          destination: documentDeleted
          group: documentDescriptorDeletedGroup
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
security:
  oauth2:
    client:
      clientId: descriptor-service
      clientSecret: descriptor-service-secret
    resource:
      loadBalanced: true
      userInfoUri: http://auth-service/uaa/user
      preferTokenInfo: false
#  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/