server:
  port: 8084
spring:
  application:
    name: document-service
  http:
    multipart:
     max-file-size: 1024KB
     max-request-size: 1024KB
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  cloud:
    stream:
      bindings:
        documentDeletedInput:
          destination: documentDeleted
          group: documentDeletedGroup
security:
  oauth2:
    client:
      clientId: document-service
      clientSecret: document-service-secret
    resource:
      loadBalanced: true
      userInfoUri: http://auth-service/uaa/user
      preferTokenInfo: false
#  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
elasticsearch:
  host: localhost
  port: 9300
  clusterName: elasticsearch
  indexName: documents
  typeName: documents
  numberOfShards: 1
  numberOfReplicas: 0
  pipelineName: attachment
