server:
  port: 8082
addToDb: true
spring:
  application:
    name: process-service
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/process?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      bindings:
        documentDeletedOutput:
          destination: documentDeleted
          contentType: application/json
        documentAddedInput:
          destination: documentAdded
          group: documentAddedGroup
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
security:
  oauth2:
    resource:
      loadBalanced: true
      userInfoUri: http://auth-service/uaa/user
#      preferTokenInfo: false
#  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/